export const FETCH_POST = "POST/FETCH_POST";
export const FETCH_COMMENTS = "POST/FETCH_COMMENTS";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const FETCH_USER = "USER/FETCH_USER";
